# Generated by Django 5.0.6 on 2026-07-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_pendingaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='bot_type',
            field=models.CharField(choices=[('maintenance', 'Maintenance & Help Desk Bot'), ('fee', 'Fee Bot'), ('media', 'Media Bot'), ('assignment', 'Assignment Bot'), ('exam', 'Exam Bot'), ('attendance', 'Attendance & Compliance Bot'), ('certificate', 'Certificates Bot'), ('scholarship', 'Scholarship Bot'), ('inventory', 'Inventory Bot'), ('event', 'Event Bot'), ('general', 'General Assistant')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
