# Generated by Django 5.0.6 on 2026-07-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_pendingaction'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pendingaction',
            name='pendingaction__status_created_at_idx',
        ),
    ]
