# Generated by Django 5.0.6 on 2026-07-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classsection_teacher_incharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsection',
            name='default_room',
        ),
        migrations.RemoveField(
            model_name='classsection',
            name='teacher_incharge',
        ),
    ]
